---
dist: xenial
language: node_js
node_js:
 - "node"
addons:
  - ssh_known_hosts: "$PRODUCTION_SERVER"
env: >-
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key
  -iv $encrypted_db2095f63ba3_iv -in .travis/deploy_rsa.enc -out deploy_rsa -d
