---
dist: xenial
language: clojure
addons:
    - ssh_known_hosts: "$PRODUCTION_SERVER"
env: >-
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key
  -iv $encrypted_db2095f63ba3_iv -in .travis/deploy_rsa.enc -out deploy_rsa -d
install: lein clean
script: lein cljsbuild once min
deploy:
    provider: script
    script: >-
      rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/resources
      $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER:~/helmikuu/ &&
      ssh -o "StrictHostKeyChecking no" -p22
      $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER "sh ~/helmikuu/deploy.sh"
