dist: xenial
language: clojure
lein: 2.6.1
addons:
- ssh_known_hosts: "$PRODUCTION_SERVER"
before_install: openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d && eval "$(ssh-agent -s)" && chmod 600 /tmp/deploy_rsa
  && ssh-add /tmp/deploy_rsa
build:
- provider: script
- skip_cleanup: true
- script: lein clean & lein cljsbuild once min
- branches:
    only:
    - master
deploy:
  provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/resources $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER:~/helmikuu/
    && ssh -p22 $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER "sh ~/helmikuu/deploy.sh"
env:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
