---
dist: xenial
language: clojure
addons:
  ssh_known_hosts:
    - $PRODUCTION_SERVER
env: >-
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key
  -iv $encrypted_db2095f63ba3_iv -in .travis/deploy_rsa.enc
  -out deploy_rsa -d && cp .travis/deploy_rsa /tmp/deploy_rsa
  && eval "$(ssh-agent -s)" && chmod 600 /tmp/deploy_rsa
  && ssh-add /tmp/deploy_rsa && echo -e
  "Host $PRODUCTION_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install: lein clean
script: lein cljsbuild once min
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script: >-
    rsync -r --delete-after -e "ssh -o StrictHostKeyChecking=no -o
    PubkeyAuthentication=yes -o PasswordAuthentication=no" --quiet
    resources $PRODUCTION_SERVER:~/helmikuu/&&
    ssh -o "StrictHostKeyChecking no" -p22
    $PRODUCTION_SERVER "sh ~/helmikuu/scripts/deploy.sh"
