---
dist: xenial
language: clojure
lein: 2.6.1
addons:
  - ssh_known_hosts: "$PRODUCTION_SERVER"
env: >-
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key
  -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
